learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from learning_logs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    # 指定Topic的详情页面
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # 指定"添加新主题"的页面url模式
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 指定"添加新条目"的页面url模式
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 编辑条目
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    # 编辑主题
    url(r'^edit_topic/(?P<topic_id>\d+)/$', views.edit_topic, name='edit_topic'),
]

users/urls.py
"""定义users应用程序的URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    # 登陆页面
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题(Topic)的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    """empty"""
    class Meta:
        model = Topic
        fields = ['text', 'public']
        labels = {'text': '', 'public': '设为公开'}


class Entry_form(forms.ModelForm):
    """通过获取entry模型来定制表单的属性, 该类的实例被django用来自动生成表单以及将Meta内的变量关联到数据库的Entry属性等"""
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from learning_logs.models import Topic, Entry
from.forms import TopicForm, Entry_form
from django.contrib.auth.decorators import login_required


def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


# @ login_required
def topics(request):
    """显示私有主题"""
    if request.user.is_authenticated:
        topics = Topic.objects.filter(owner=request.user).order_by('date_added')
        login_status = True
    else:
        topics = Topic.objects.filter(public=True).order_by('date_added')
        login_status = False

    context = {'topics': topics, 'login_status': login_status}  # topic键值对多写了一个colon, 好家伙找他妈俩小时!!! dear fuck!!!

    return render(request, 'learning_logs/topics.html', context)


# @ login_required
def topic(request, topic_id):
    """显示指定id的单个主题及其条目"""

    # 向数据库查询, 建议先在django shell当中尝试, 以确认无误
    # topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    # if topic.owner != request.user:
    #     raise Http404
    entries = topic.entry_set.order_by('-date_added')

    context = {'topic': topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)


@ login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据, 创建新表单
        form = TopicForm()
    else:
        # POST提交数据, 对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))  # reverse反向解析URL

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@ login_required
def new_entry(request, topic_id):
    """通过id获取要添加新条目的主题"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 未提交创建空表单
        form = Entry_form()
    else:
        # 提交, 获取请求中的数据, 存入数据库, 并重定向到topic页面
        form = Entry_form(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic  # 关联到主题
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@ login_required
def edit_entry(request, entry_id):
    """编辑条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # 使用当前entry填充表单
        form = Entry_form(instance=entry)
    else:
        form = Entry_form(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def edit_topic(request, topic_id):
    """编辑主题"""
    topic = get_object_or_404(Topic, id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != "POST":
        # 使用当前主题填充表单
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """注销登录"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        form = UserCreationForm()  # 显示空注册表单
    else:
        # 处理填写好的POST提交的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录, 然后重定向到主页
            authenticate_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="{% static 'jquery-3.5.1.js' %}"></script>

    <title>学习笔记</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery=True %}

</head>
<body>
    <!-- Static navbar 静态导航栏-->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">展开
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">学习笔记首页</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li><!-- 这里不放a标签,jiu不对齐了 -->
                        <li><a href="{% url 'users:logout' %}">注销</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">注册</a></li>
                        <li><a href="{% url 'users:login' %}">登陆</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->

        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div><!--容器container-->

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑条目</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}
        <p><a>返回topic:{% url 'learning_logs:topic' topic.id %}</a></p>

        <p>编辑条目:{{ entry }}</p>
        <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">提交修改</button>
        </form>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改主题名</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% load bootstrap3 %}

    {% block header %}
        <h2>编辑主题</h2>
    {% endblock header %}

    {% block content %}

        <form method="post" class="form" action="{% url 'learning_logs:edit_topic' topic.id %}">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
                <button class="btn btn-primary" name="submit">提交修改</button>
            {% endbuttons %}
        </form>

    {% endblock content %}
    
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学习笔记主页</title>
</head>
<body>
    {#<p>Learning Log</p>#}
    <!--注释-->
    {% extends "learning_logs/base.html" %}
    {% block header %}
        <div class="jumbotron">
            <h1>Track your learning.</h1>
        </div>
    {% endblock header %}

    {% block content %}
        {#<div id="welcome">{{ user.username }}欢迎来到学习笔记!</div>#}
        <h2>
            <a href="{% url 'users:register' %}">注册你的学习笔记</a>来生成你专属的学习笔记, 并列出你正在学习的主题
        </h2>
        <h2>Learning log helps you keep track of your learning, for any topic you are learning about.</h2>
        <h2>学习笔记帮助你跟踪任何你正在学习的主题的学习情况.</h2>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新增条目</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% load bootstrap3 %}

    {% block header %}
        <h2>归属主题:<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
        <h2>新增条目:</h2>
    {% endblock header %}

    {% block content %}

        <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
{#            {{ form.as_p }}#}
            {% buttons %}
                <button name="submit" class="btn btn-primary">add new entry</button>
            {% endbuttons %}
        </form>

    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新建页面</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% load bootstrap3 %}

    {% block header %}
        <h2>新建页面</h2>
    {% endblock header %}

    {% block content %}

        <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
            {% csrf_token %}
{#            {{ form.as_p }}#}
            {% bootstrap_form form %}

            {% buttons %}
                <button name="submit" class="btn btn-primary">add topic</button>
            {% endbuttons %}
        </form>

    {% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>topic</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block header %}
        <h2>{{ topic }}</h2>
    {% endblock header %}

    {% block content %}

        <p>
            <a href="{% url 'learning_logs:edit_topic' topic.id %}">修改主题名</a>
            <a href="{% url 'learning_logs:new_entry' topic.id %}">新建条目(Add Entry)</a>
        </p>

        {% for entry in entries %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>
                        {{ entry.date_added|date:'M d, Y H:i' }}
                        <small>
                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑条目</a>
                        </small>
                    </h3>
                </div>

                <div class="panel-body">
                    {{ entry.text|linebreaks }}
                </div>
            </div><!-- panel -->
        {% empty %}
            Nothing to show, sorry.
        {% endfor %}

    {% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>所有主题</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}

    {% block header %}
        <h3>Topics</h3>
        {% if not login_status %}
            <h4>未登录用户仅他妈的能查看公开主题</h4>
        {% endif %}
    {% endblock header %}

    {% block content %}

        <ul>
            {% for topic in topics %}
                <li>
                {% if topic.public == True %}
                    <h3>
                        <a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}
                        -用户({{ topic.owner }})-公开</a>
                    </h3>
                {% else %}
                    <h3>
                        <a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}
                        -用户({{ topic.owner }})-私有</a>
                    </h3>
                {% endif %}
                </li>
            {% empty %}
                <li>no topics have been added yet.</li>
            {% endfor %}
        </ul>

        <h3><a href="{% url 'learning_logs:new_topic' %}">add new topic</a></h3>

    {% endblock content %}

</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset='UTF-8'>
		<title>登陆</title>
	</head>
	<body>
		{% extends 'learning_logs/base.html' %}
        {% load bootstrap3 %}

        {% block header %}
            <h2>登录你的账户</h2>
        {% endblock header %}

        {% block content %}
            <!--此块删除, 因为django-bootstrap3自动处理表单错误-->
{#            {% if form.errors %}#}
{#                <p>用户名或密码错误</p>#}
{#            {% endif %}#}

            <form method="post" action="{% url 'users:login' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {# {{ form.as_p }} 被上面这句取代#}

            {% buttons %}
            <button name="submit" class="btn btn-primary">登录</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
            </form>
        {% endblock content %}

	</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% block content %}
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            {{ form.as_p }}

        <button name="submit">注册</button>
        {#<input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />#}
        </form>
    {% endblock content %}
</body>
</html>